- name: "Install jenkins proxy template"
  template:
    src: jenkins.j2
    dest: /etc/nginx/sites-available/jenkins
  notify: restart nginx
- name: "Enable jenkins proxying"
  file:
    src: /etc/nginx/sites-available/jenkins
    dest: /etc/nginx/sites-enabled/jenkins
    state: link
  notify: restart nginx
