- name: "Create CI group"
  group:
    name: "{{ ci_group }}"
    state: present
- name: "Create CI user"
  user:
    name: "{{ ci_user }}"
    shell: /bin/bash
    groups: docker,{{ ci_group }}
    group: "{{ ci_group }}"
    state: present
    createhome: yes
    home: "{{ ci_home }}"
  notify:
    - restart docker
- name: "Create dedicated network"
  docker_network:
    name: '{{ ci_docker_network }}'
    state: present
