- name: "Pull nexus container"
  docker_image:
    name: sonatype/nexus3:{{ nexus_version }}
    state: present
- name: "Start nexus container"
  docker_container:
    name: nexus
    image: sonatype/nexus3:{{ nexus_version }}
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "{{ nexus_port }}:8081"
    networks:
      - name: "{{ ci_docker_network }}"
- name: "Create nexus service descriptor"
  template:
    src: nexus-ci.service.j2
    dest: /etc/systemd/system/nexus-ci.service
- name: "Enable nexus service"
  service:
    name: nexus-ci
    enabled: yes
    state: started
