- name: "Add docker repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
- name: "Install docker repository key"
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: "Install docker"
  apt:
    name: docker-ce
    update_cache: yes
    state: present
- name: "Install docker-compose"
  apt:
    name: docker-compose
    state: present
